# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68901906f9c54bc4223b04cd71c67d257c9dd857cd53358d2bb3075ce04e6553c13966d2a55834524237a517d66d345c1dec8d0573de1801270957b09302fdcc

test:
  secret_key_base: 5fd024055bd05ed7f0b603ee510f639112959ab31d1d74ea36b8988831cd04ab8dccac8ef8508f1498cb7e0c47a316a8f30fe1a144579df03adb2bc21be64c40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
